baseURL = 'https://mullenixfiber.org'
languageCode = 'en-us'
title = 'Mullenix Fiber Petition'
sectionPagesMenu = 'main'

[markup.goldmark.renderer]
unsafe = true

[module]
[module.hugoVersion]
extended = true
min = "0.73.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false

[params]
[params.ui]
showLightDarkModeMenu = true
